## Activity 03: Filtering, Sorting, and Reshaping

Following up on the last activity, we are asked to deliver some more complex operations.   
We will, therefore, continue to work with the same dataset, our `normal_distribution.csv`.

#### Loading the dataset

In [1]:
# importing the necessary dependencies
import numpy as np

In [2]:
# loading the Dataset
dataset = np.genfromtxt('normal_distribution.csv', delimiter=',')

---

#### Filtering

To get better insights into our dataset, we want to only look at the value that fulfills certain conditions.   
Our client reaches out to us and asks us to provide lists of values that fulfills these conditions:
- all values greater than 105 (>105)
- all values that are between 90 and 95 (>90 and <95)
- the indices of all values that have a delta of less than 1 to 100 (x-100 < 1)

In [4]:
# values that are greater than 105
dataset[dataset > 105]

array([107.43534677, 105.7197853 , 110.18889465, 105.95297652,
       106.54654286, 113.42090475, 105.48508838, 106.1472841 ,
       105.85269352, 108.57980357, 106.71751618, 106.39798503,
       106.83273763, 106.47551845, 105.30350449, 106.03868807,
       110.44484313, 106.6471081 , 105.0320535 , 107.02874163,
       105.07475277, 107.22482426, 107.19119932, 108.09423367,
       109.40523174, 106.11454989, 106.57052697, 105.13668343,
       105.37011896, 105.86078488, 106.89005002, 106.57364584,
       107.40064604, 106.38276709, 106.46476468, 110.43976681,
       105.02389857, 106.05042487])

In [5]:
# values that are between 90 and 95
dataset[(dataset > 90) & (dataset < 95)]

array([92.02628776, 92.9267508 , 92.65657752, 90.93318132, 91.37294597,
       91.6604946 , 93.37126331, 94.20019732, 93.24376389, 94.35373179,
       92.5748759 , 92.87730812, 93.87155456, 92.75048583, 91.32093303,
       92.0108226 , 93.18884302, 93.83969256, 94.5081787 , 94.59300658,
       93.04610867, 91.6779221 , 94.76253572, 94.57421727, 94.11176915,
       93.97853495])

> **Note:**    
Conditional filtering can be done either using the brackets syntax or NumPys `extract` method

In [6]:
# indices of values that have a delta of less than 1 to 100

np.where((dataset - 100) < 1)

(array([ 0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,
         3,  3,  3,  3,  3,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,
         6,  7,  7,  7,  7,  8,  8,  9,  9,  9,  9, 10, 10, 10, 10, 10, 11,
        11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14,
        15, 15, 15, 15, 15, 15, 16, 16, 16, 17, 17, 17, 17, 18, 18, 18, 18,
        18, 19, 19, 19, 19, 20, 20, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22,
        23, 23, 23, 23, 23, 23], dtype=int64),
 array([0, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 0, 1, 2, 4, 6, 0, 1, 2, 5, 7,
        2, 4, 6, 7, 1, 2, 3, 4, 5, 2, 3, 5, 6, 0, 5, 6, 7, 1, 5, 1, 3, 4,
        6, 1, 3, 5, 6, 7, 0, 3, 4, 7, 0, 4, 5, 6, 0, 1, 2, 3, 4, 6, 7, 2,
        3, 5, 1, 2, 3, 5, 6, 7, 0, 1, 6, 2, 3, 5, 6, 0, 1, 5, 6, 7, 0, 1,
        4, 6, 4, 7, 0, 4, 5, 7, 0, 1, 2, 4, 5, 6, 0, 1, 3, 4, 5, 7],
       dtype=int64))

---

#### Sorting

They also want to experiment with some more plotting techniques so they ask you to also deliver these datasets:
- values sorted in ascending order for each row
- values sorted in ascending order for each column
- the matrix of indices indicating the position in a sorted list of each value   
```
[3, 1, 2, 5, 4]  =>  [1, 2, 0, 4, 3]
```

In [8]:
# values sorted for each row
np.sort(dataset, axis=1)

array([[ 96.81964892,  97.85230675,  98.56783189,  98.74986914,
         98.80833412,  99.14931546, 104.03852715, 107.43534677],
       [ 92.02628776,  92.65657752,  92.9267508 ,  97.10439252,
         97.24584816,  99.32066924, 101.23162942, 105.7197853 ],
       [ 90.93318132,  95.17750125,  95.66253664,  98.37481387,
         98.80084371, 105.95297652, 106.54654286, 110.18889465],
       [ 91.37294597,  91.6604946 ,  95.08715803, 100.40118279,
        100.96781394, 105.48508838, 106.1472841 , 113.42090475],
       [ 93.37126331,  94.20019732, 100.28690912, 100.79478953,
        101.20862522, 103.5730309 , 105.85269352, 108.57980357],
       [ 89.03452725,  93.24376389,  96.2832753 ,  97.24130034,
         98.29687616, 101.13442416, 102.80387079, 104.60344836],
       [ 94.35373179,  95.46493436,  98.45723272, 100.72418901,
        102.97585605, 106.39798503, 106.71751618, 106.83273763],
       [ 92.5748759 ,  96.02548256,  97.57544275,  98.74767493,
        101.34745901, 102.4565179

> **Note:**   
By default, sorting will always be done along the last axis. In our case this is 1, leading to each row being sorted.

In [9]:
# values sorted for each column
np.sort(dataset, axis=0)

array([[ 91.37294597,  88.80221141,  90.93318132,  93.18884302,
         85.98839623,  91.6604946 ,  91.32093303,  92.5748759 ],
       [ 92.02628776,  91.6779221 ,  93.24376389,  94.59300658,
         89.03452725,  92.65657752,  93.04610867,  94.20019732],
       [ 94.11176915,  92.0108226 ,  93.83969256,  96.74630281,
         92.75048583,  95.19184343,  94.35373179,  94.76253572],
       [ 95.65982034,  92.87730812,  94.5081787 ,  97.24130034,
         92.9267508 ,  95.46493436,  96.50342927,  95.08715803],
       [ 95.66253664,  93.87155456,  97.75887636,  97.24584816,
         93.37126331,  95.62359311,  96.81964892,  95.85284217],
       [ 96.02548256,  94.57421727,  98.45723272,  97.62787811,
         93.97853495,  96.2832753 ,  96.89244283,  97.59572169],
       [ 96.10020311,  95.17750125,  99.32066924,  97.65393524,
         95.93799169,  96.34622848,  96.96851209,  98.00253006],
       [ 96.76814836,  96.59385486,  99.57859892,  97.85230675,
         98.29243952,  96.5937781

In [10]:
# indices of positions for each row
all_indices = []
for i, row in enumerate(dataset, 0):
    row_indices = []
    for j, column in enumerate(row, 0):
        row_indices.append([i, j])
    all_indices.append(row_indices)
    
print(all_indices)        

[[[0, 0], [0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [0, 6], [0, 7]], [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [1, 7]], [[2, 0], [2, 1], [2, 2], [2, 3], [2, 4], [2, 5], [2, 6], [2, 7]], [[3, 0], [3, 1], [3, 2], [3, 3], [3, 4], [3, 5], [3, 6], [3, 7]], [[4, 0], [4, 1], [4, 2], [4, 3], [4, 4], [4, 5], [4, 6], [4, 7]], [[5, 0], [5, 1], [5, 2], [5, 3], [5, 4], [5, 5], [5, 6], [5, 7]], [[6, 0], [6, 1], [6, 2], [6, 3], [6, 4], [6, 5], [6, 6], [6, 7]], [[7, 0], [7, 1], [7, 2], [7, 3], [7, 4], [7, 5], [7, 6], [7, 7]], [[8, 0], [8, 1], [8, 2], [8, 3], [8, 4], [8, 5], [8, 6], [8, 7]], [[9, 0], [9, 1], [9, 2], [9, 3], [9, 4], [9, 5], [9, 6], [9, 7]], [[10, 0], [10, 1], [10, 2], [10, 3], [10, 4], [10, 5], [10, 6], [10, 7]], [[11, 0], [11, 1], [11, 2], [11, 3], [11, 4], [11, 5], [11, 6], [11, 7]], [[12, 0], [12, 1], [12, 2], [12, 3], [12, 4], [12, 5], [12, 6], [12, 7]], [[13, 0], [13, 1], [13, 2], [13, 3], [13, 4], [13, 5], [13, 6], [13, 7]], [[14, 0], [14, 1], [14, 2], [14, 3], [14, 4

---

#### Combining

After finishing their visualization and doing ask you to deliver a way they can incrementally add the split parts of the dataset to make sure it works with every subset, too.   
They want you to send them examples for:
- adding the second half of the first column
- adding the second column
- adding the third and last separate column


In [13]:
# split up dataset from activity03
index1 = len(dataset[0]) // 3
index2 = 2 * index1
thirds = np.hsplit(dataset, [index1, index2])
halfed_first = np.vsplit(thirds[0], (2))

# this is the part we've sent the client in activity03
halfed_first[0]

array([[ 99.14931546, 104.03852715],
       [ 92.02628776,  97.10439252],
       [ 95.66253664,  95.17750125],
       [ 91.37294597, 100.96781394],
       [101.20862522, 103.5730309 ],
       [102.80387079,  98.29687616],
       [106.71751618, 102.97585605],
       [ 96.02548256, 102.82360856],
       [105.30350449,  92.87730812],
       [110.44484313,  93.87155456],
       [101.3514185 , 100.37372248],
       [ 97.21315663, 107.02874163]])

In [14]:
# adding the second half of the first column to the data
combined_dataset = np.vstack([halfed_first[0], halfed_first[1]])
combined_dataset

array([[ 99.14931546, 104.03852715],
       [ 92.02628776,  97.10439252],
       [ 95.66253664,  95.17750125],
       [ 91.37294597, 100.96781394],
       [101.20862522, 103.5730309 ],
       [102.80387079,  98.29687616],
       [106.71751618, 102.97585605],
       [ 96.02548256, 102.82360856],
       [105.30350449,  92.87730812],
       [110.44484313,  93.87155456],
       [101.3514185 , 100.37372248],
       [ 97.21315663, 107.02874163],
       [ 95.65982034, 107.22482426],
       [100.39303522,  92.0108226 ],
       [103.1521596 , 109.40523174],
       [106.11454989,  88.80221141],
       [ 96.78266211,  99.84251605],
       [101.86186193, 103.61720152],
       [ 97.49594839,  96.59385486],
       [ 96.76814836,  91.6779221 ],
       [106.89005002, 106.57364584],
       [ 99.80873105, 101.63973121],
       [ 96.10020311,  94.57421727],
       [ 94.11176915,  99.62387832]])

In [15]:
# adding the second column to our combined dataset
combined_dataset = np.hstack([combined_dataset, thirds[1]])
combined_dataset

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901],
       [105.30350449,  92.87730812, 103.19258339, 104.40518318],
       [110.44484313,  93.87155456, 101.5363647 ,  97.65393524],
       [101.3514185 , 100.37372248, 106.6471081 , 100.61742813],
       [ 97.21315663, 107.02874163, 102.17642112,  96.74630281],
       [ 95.65982034, 107.22482426, 107.19119932, 102.93039474],
       [100.39303522,  92.0108226 ,  97.75887636,  93.18884302],
       [103.1521596 , 109.40523174,  93.83969256,  99.95827854],
       [106.11454989,  88

In [16]:
# adding the third column to our combined dataset
combined_dataset = np.hstack([combined_dataset, thirds[2]])
combined_dataset

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.46493436,  94.35373179, 106.83273763],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.7476749

> **Note:**    
The same results can be achieved with `np.concatenate` and `np.stack`.    
For both methods, you need to provide the axis onto which it should be appended.   
Depending on your preferences you might want to use those.

---

#### Reshaping

For their internal AI algorithms, they need the dataset in a reshaped manner that reduces the number of columns.   
They asked us to deliver the whole dataset in the following shapes:
- reshaped in a one-dimensional list with all values
- reshaped in a matrix with only 2 columns

In [19]:
# reshaping to a list of values
dataset = np.array(dataset)
dataset.reshape(1, dataset.size)

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189,
         92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942,
         95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286,
         91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803,
        101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732,
        102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416,
        106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.46493436,  94.35373179, 106.83273763,
         96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.74767493,  97.

In [21]:
# reshaping to a matrix with two columns
dataset.reshape((dataset.size)//2, -1)

array([[ 99.14931546, 104.03852715],
       [107.43534677,  97.85230675],
       [ 98.74986914,  98.80833412],
       [ 96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252],
       [ 99.32066924,  97.24584816],
       [ 92.9267508 ,  92.65657752],
       [105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125],
       [ 90.93318132, 110.18889465],
       [ 98.80084371, 105.95297652],
       [ 98.37481387, 106.54654286],
       [ 91.37294597, 100.96781394],
       [100.40118279, 113.42090475],
       [105.48508838,  91.6604946 ],
       [106.1472841 ,  95.08715803],
       [101.20862522, 103.5730309 ],
       [100.28690912, 105.85269352],
       [ 93.37126331, 108.57980357],
       [100.79478953,  94.20019732],
       [102.80387079,  98.29687616],
       [ 93.24376389,  97.24130034],
       [ 89.03452725,  96.2832753 ],
       [104.60344836, 101.13442416],
       [106.71751618, 102.97585605],
       [ 98.45723272, 100.72418901],
       [106.39798503,  95.46493436],
 

In [22]:
# reshaping to a matrix with two columns
dataset.reshape(-1, 2)

array([[ 99.14931546, 104.03852715],
       [107.43534677,  97.85230675],
       [ 98.74986914,  98.80833412],
       [ 96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252],
       [ 99.32066924,  97.24584816],
       [ 92.9267508 ,  92.65657752],
       [105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125],
       [ 90.93318132, 110.18889465],
       [ 98.80084371, 105.95297652],
       [ 98.37481387, 106.54654286],
       [ 91.37294597, 100.96781394],
       [100.40118279, 113.42090475],
       [105.48508838,  91.6604946 ],
       [106.1472841 ,  95.08715803],
       [101.20862522, 103.5730309 ],
       [100.28690912, 105.85269352],
       [ 93.37126331, 108.57980357],
       [100.79478953,  94.20019732],
       [102.80387079,  98.29687616],
       [ 93.24376389,  97.24130034],
       [ 89.03452725,  96.2832753 ],
       [104.60344836, 101.13442416],
       [106.71751618, 102.97585605],
       [ 98.45723272, 100.72418901],
       [106.39798503,  95.46493436],
 

> **Note:**   
-1 in the dimension definition means that it figures out the other dimension on its own