In [1]:
import numpy as np

### Vectors

In [4]:
myList = [1, 2, 3]
type(myList), myList

(list, [1, 2, 3])

In [5]:
row_vector = np.array(myList)
type(row_vector), row_vector

(numpy.ndarray, array([1, 2, 3]))

In [6]:
row_vector.ndim

1

In [7]:
row_vector.size

3

In [8]:
row_vector.shape

(3,)

### Matrix

In [11]:
nestedList = [[1, 2], [3, 4], [5, 6]]
type(nestedList), nestedList

(list, [[1, 2], [3, 4], [5, 6]])

In [12]:

matrix = np.array(nestedList)
type(matrix), matrix

(numpy.ndarray,
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [13]:
matrix.ndim

2

In [14]:
matrix.size

6

In [15]:
matrix.shape

(3, 2)

### 3D 

In [18]:
oneD = np.array([1 ,2])
oneD.ndim, oneD.size, oneD.shape, oneD

(1, 2, (2,), array([1, 2]))

In [23]:
twoD = np.array([oneD, oneD])
twoD.ndim, twoD.size, twoD.shape, twoD

(2,
 4,
 (2, 2),
 array([[1, 2],
        [1, 2]]))

In [26]:
threeD = np.array([twoD, twoD])
threeD.ndim, threeD.size, threeD.shape, threeD

(3,
 8,
 (2, 2, 2),
 array([[[1, 2],
         [1, 2]],
 
        [[1, 2],
         [1, 2]]]))

In [28]:
threeD[0][0][1] = 9

In [29]:
threeD

array([[[1, 9],
        [1, 2]],

       [[1, 2],
        [1, 2]]])

In [32]:
import time

In [42]:
myList = range(100000000)

In [43]:

st = time.time()
sumX = 0
for i in myList:
    sumX += i
print('Sum: ', sumX)
et = time.time()
print(et - st)

Sum:  4999999950000000
5.595837116241455


In [45]:

st = time.time()
np.sum(myList)
print('Sum: ', sumX)
et = time.time()
print(et - st)

Sum:  4999999950000000
7.713512897491455
